swagger: "2.0"
info:
  description: "here is my Restarant service api documentation."
  version: "1.0.0"
  title: "Swagger Restarant"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
  - name: "user"
    description: "Access data from users"
schemes:
  - "http"
  - "https"
paths:
  /register:
    post:
      tags:
        - "user"
      summary: "post user"
      description: ""
      operationId: "placeOrder"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "order placed for purchasing the pet"
          required: true
          schema:
            $ref: "#/definitions/Order"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/OrderSucess"
        "404":
          description: "Invalid Order"
          schema:
            $ref: "#/definitions/OrderFaliure"
  /login:
    post:
      tags:
        - "user"
      summary: "post the user data"
      description: ""
      operationId: "placeOrder"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "order placed for purchasing the pet"
          required: true
          schema:
            $ref: "#/definitions/Login"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/LoginSucess"
        "401":
          description: "Invalid Order"
          schema:
            $ref: "#/definitions/LoginFaliure"

definitions:
  Order:
    type: "object"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
  OrderSucess:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"

  OrderFaliure:
    type: "object"
    properties:
      status:
        type: "integer"
      message:
        type: "string"

  Login:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
  LoginSucess:
    type: "object"
    properties:
      access_token:
        type: "string"
      token_type:
        type: "string"
      expires_in:
        type: "integer"

  LoginFaliure:
    type: "object"
    properties:
      error:
        type: "string"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
